### ISSUE TITLE
When a search result is selected, should the Student Search window close?

### ISSUE THREAD

**Issue by AlexArendsen** [ucfcba/labman_scanner#17]
Currently, when a search result is selected from the Student Search window, it closes. Should it remain open instead?

**Comment by keontestingcenter** [comment]
That depends. Are you able to have the picture thumbnail? If not, they may need to select multiple students until they get the correct one. A possible solution, if the thumbnail cannot be done, is to only show students who have exams/exceptions available.

**Comment by AlexArendsen** [comment]
We unfortunately don't have the resources the amount of system load associated with adding thumbnails to student search results. Right now there isn't a reliable way with the library to efficiently denote students who are likely to be checked in or out by the scanner either.

I think the easiest solution will be to leave the student search window open in the background when a student is selected, and if the user taps the "Search" button, it will just bring the existing search window into the foreground again.

**Comment by keontestingcenter** [comment]
So, 

if student has test open, show student

if student does not have test open, do not show student

isn't possible?

But, select student, show open exams is possible?

**Comment by AlexArendsen** [comment]
Sorry, I should have thought more about my response-- both are absolutely possible.

The first (filtering student search results) will just take a little more development time, because it was not planned for when we started, and I'll have to work it into the library. I'll have no problem doing it though! I'll open a ticket when I get back from class.
