### ISSUE TITLE
Check-in Correction Feature

### ISSUE THREAD

**Issue by AlexArendsen** [ucfcba/labman_scanner#5]
Feature idea: provide a view of currently checked in students, in ascending order of check-in (ie, students checked furthest in the past are displayed first). The check-in date and time should be noted, along with an English descriptor of how long ago the check-in was (ie, "two hours ago", "three days ago", etc.)

Each record will have a control to manually check the student out. The test's length and average time should be provided to help the manager decide on an appropriate check-out date and time. Absolute date-time controls (allowing the user to enter an absolute check-out date and time), as well as relative ones (allowing the user to specify some number of minutes after check-in) should be provided, with the latter being the default option.

Voice your opinions below.

**Comment by keontestingcenter** [comment]
Word

**Comment by keontestingcenter** [comment]
LabAdmin though. Not Lab Scanner

**Comment by AlexArendsen** [comment]
Roger, moving it now.
