### ISSUE TITLE
Iteration 1: Student information display

### ISSUE THREAD

**Issue by AlexArendsen** [ucfcba/labman_scanner#9]
Make a way to display a student's name, image, and notes on the left of the display without binding it to a particular UI event (have it triggered by a button or something, temporarily).

**Comment by keontestingcenter** [comment]
Just a thought. The check in/out screens should not change whenever an ID is swiped. So, let's say a lab assistant swipes a students ID, does the whole check in process, forgets to hit ADMIT or RELEASE, then swipes another students ID, it should prompt them to do some sort of action with the current students information.

**Comment by AlexArendsen** [comment]
I can do that. I would like to make it an "Are you sure?" popup, however. Otherwise, if the staff member genuinely doesn't need to admit or release the student (eg, the student was mistaken about their test status, or the staff member selected a random student from "Search Students"), they could get stuck and would have to restart the scanner.

Should I have this popup display when a student is selected form the "Search Students" window as well?

**Comment by keontestingcenter** [comment]
Yes

**Comment by AlexArendsen** [comment]
Super! I'll get working on that now!

**Comment by AlexArendsen** [comment]
Done!
